services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6666:6666"
    environment:
      - DATABASE_URL=postgres://togo_user:togo_password@db:5432/togo_db?sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: togo_user
      POSTGRES_PASSWORD: togo_password
      POSTGRES_DB: togo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
