services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: togo_user
      POSTGRES_PASSWORD: togo_password
      POSTGRES_DB: togo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


